version: '3'
services:
    metrics:
        build:
            context: .
#            args:
#                arguments: "ps cpu mem disk"
        image: test_task_lerkasan:latest
        container_name: test_task_lerkasan
        pid: host
        ipc: host
        privileged: true   #Use privileged mode to see read/write bytes of host processes
        environment:
            - arguments=ps cpu mem disk
        volumes:
            - "/etc/passwd:/etc/passwd:ro"
            - "/proc:/host/proc:ro"
