version: '3'
services:
    metrics:
        build: .
        image: test_task_lerkasan:latest
        container_name: test_task_lerkasan
        pid: host          # "--pid host" option is used to be able to see host processes inside docker container
        privileged: true   # Use privileged mode to see read/write bytes of host processes inside docker container
        environment:
            - arguments=ps cpu mem disk
        volumes:
            - "/etc/passwd:/etc/passwd:ro"  # /etc/passwd file is mounted as volume to be able to see host usernames in process list inside docker container
            - "/proc:/host/proc:ro"         # /proc folder is mounted to be able to get read/write in bytes metric of host processes
