#!/usr/bin/env python3

import os
import sys
import psutil
import time
import datetime

# PROCFS_PATH is used by psutils to calculate processes "read/write bytes" metric
# Default value is "/proc"
# For docker container value "/host/proc" is set in Dockerfile
if 'PROCFS_PATH' in os.environ:
    psutil.PROCFS_PATH = os.environ.get("PROCFS_PATH")


# Nicely formatted printed output of psutil tuple results passed as stats argument
def print_given_stats(stats, **kwargs):
    end = kwargs.get('end', None)
# named argument instructs whether to print metrics name before value (e.g printing two columns: left metrics name, right metrics value).
# If named argument is omitted than metrics name is printed by default.
# It's useful to set named=False when a table is printed and metrics names are placed in header row of the table rather then in left column.
    named = kwargs.get('named', None)
    if end is None:
        if named or named is None:
            for stat in stats._fields:
                print('%-20s %-20s' % (stat, getattr(stats, stat)))
        else:
            for stat in stats._fields:
                print('%-25s' % getattr(stats, stat))
    else:
        if named or named is None:
            for stat in stats._fields:
                print('%-20s %-20s' % (stat, getattr(stats, stat)), end=end)
        else:
            for stat in stats._fields:
                print('%-25s' % getattr(stats, stat), end=end)
        print()


# Nicely formatted printed output in bytes, MB and GB of psutil memory or I/O results passed as stats argument
def print_in_mb_gb(stats):
    print('Usage in: %13s %12s %9s' % ('bytes', 'MB', 'GB'))
    for stat in stats._fields:
        size_in_mb = getattr(stats, stat) / 1024 / 1024
        size_in_gb = size_in_mb/1024
        if stat is not 'percent':
            print('%-15s %-15s %-10.2f %-10.2f' % (stat, getattr(stats, stat), size_in_mb, size_in_gb))
    print('Usage in percent: %-20s' % (getattr(stats, 'percent')))


def print_memory_stats():
    mem_stats = psutil.virtual_memory()
    print('\nMemory usage:')
    print_in_mb_gb(mem_stats)
    mem_stats = psutil.swap_memory()
    print('\nSwap usage:')
    print_in_mb_gb(mem_stats)


def print_cpu_stats():
    psutil.cpu_percent(interval=None)
    psutil.cpu_times_percent(interval=None)
    print('\nCPU usage in percents:')
    print_given_stats(psutil.cpu_times_percent(interval=0.5))  #Interval 0.5 gives more reliable cpu usage percents than intervals less than 0.5
    print('\nCPU times:')
    print(print_given_stats(psutil.cpu_times()))


def print_disk_stats():
    print("\nDisk partitions:")
    disk_partitions = psutil.disk_partitions()
    for stat in disk_partitions[0]._fields:
        print('%-25s' % stat, end='    ')
    print()
    for partition in disk_partitions:
        print_given_stats(partition, named=False, end='    ')
    for partition in disk_partitions:
        mountpoint = getattr(partition, 'mountpoint')
        print("\nUsage of partition: %s" % mountpoint)
        print_in_mb_gb(psutil.disk_usage(mountpoint))
    print("\nI/O statistics:")
    print_given_stats(psutil.disk_io_counters())


def print_processes():
    print("\n%-10s %-25s %-40s %-10s %-15s %-25s %-8s %-8s %-15s %-15s %-15s %-15s"
          % ('pid', 'user', 'process', 'parent', 'status', 'started', 'CPU %', 'RAM %', 'read bytes', 'written bytes', 'read MB', 'written MB'))
    for proc in psutil.process_iter(
            attrs=['pid', 'name', 'username', 'ppid', 'status', 'create_time', 'memory_percent']):
        proc.cpu_percent(interval=None)
        with proc.oneshot():
            started = datetime.datetime.fromtimestamp(proc.create_time()).strftime("%d-%m-%Y %H:%M:%S")
            pid = proc.info['pid']
            io_file = psutil.PROCFS_PATH + "/" + str(pid) + "/io"
# /proc/{pid}/io file for many system processes is accessible only if script is executed by root. So check of accessibility is needed
            if not os.access(io_file, os.R_OK):
                print("%-10s %-25s %-40s %-10s %-15s %-25s %-8.2f %-8.2f %-15s %-15s %-15s %-15s" % (
                    proc.pid, proc.username(), proc.name(), proc.ppid(), proc.status(), started,
                    proc.cpu_percent(interval=0.1), proc.memory_percent(), 'n/a', 'n/a', 'n/a', 'n/a'))
            else:
                try:
                    io_count = proc.io_counters()
                    read_bytes = getattr(io_count, 'read_bytes')
                    write_bytes = getattr(io_count, 'write_bytes')
                    print("%-10s %-25s %-40s %-10s %-15s %-25s %-8.2f %-8.2f %-15s %-15s %-15.2f %-15.2f" % (
                        proc.pid, proc.username(), proc.name(), proc.ppid(), proc.status(), started,
                        proc.cpu_percent(interval=0.1), proc.memory_percent(), read_bytes, write_bytes, read_bytes/1024/1024, write_bytes/1024/1024))
                except psutil._exceptions.AccessDenied:
                    print("%-10s %-25s %-40s %-10s %-15s %-25s %-8.2f %-8.2f %-15s %-15s %-15s %-15s" % (
                        proc.pid, proc.username(), proc.name(), proc.ppid(), proc.status(), started,
                        proc.cpu_percent(interval=0.1), proc.memory_percent(), 'n/a', 'n/a', 'n/a', 'n/a'))


# Prints info about this script execution environment
def print_program_info():
    print("Environment variables: ", psutil.Process().environ())
    print("Memory usage by current script: ", psutil.Process().memory_percent(), "%")
    print("CPU usage by current script: ", psutil.Process().cpu_percent(), "%")
    print("Current folder: ", psutil.Process().cwd())
    print("Current user: ", psutil.Process().username())


# Returns total CPU usage time in seconds since boot
# Used in Custom alternative calculation to psutil.Process.cpu_percent()
def cpu_usage_time_since_boot():
    total_cpu_time_since_boot = 0
    stats = psutil.cpu_times()
    for stat in stats._fields:
        total_cpu_time_since_boot += getattr(stats, stat)
    total_cpu_idle_time_since_boot = getattr(stats, 'idle') + getattr(stats, 'iowait')
    total_cpu_usage_time_since_boot = total_cpu_time_since_boot - total_cpu_idle_time_since_boot
    return total_cpu_usage_time_since_boot


# Custom alternative calculation to psutil.Process.cpu_times(). Just to compare results with psutil
def proc_cpu_time(pid):
    proc_times = 0
    proc = psutil.Process(pid)
    proc_cpu_times = proc.cpu_times()
    for stat in proc_cpu_times._fields:
        if stat not in ['idle', 'iowait']:
            proc_times += getattr(proc_cpu_times, stat)
    return proc_times


# Custom alternative calculation to psutil.Process.cpu_percent(). Just to compare results with psutil
def proc_cpu_percent(pid):
    previous_cpu_usage_time_since_boot = cpu_usage_time_since_boot()
    previous_proc_times = proc_cpu_time(pid)

    time.sleep(2)

    current_cpu_usage_time_since_boot = cpu_usage_time_since_boot()
    current_proc_times = proc_cpu_time(pid)

    dif_cpu_usage_time = current_cpu_usage_time_since_boot - previous_cpu_usage_time_since_boot
    dif_proc_times = current_proc_times - previous_proc_times
    proc_cpu_time_percent = 100 * dif_proc_times / dif_cpu_usage_time
    return proc_cpu_time_percent


def application():
    stat_args = [('cpu', print_cpu_stats),
                 ('mem', print_memory_stats),
                 ('disk', print_disk_stats),
                 ('ps', print_processes),
                 ('self', print_program_info)
                ]

    args = ''
    valid_args_count = 0

# Ignores invalid arguments (not listed in stat_args) and prints metrics only about valid arguments
    for program_arg in sys.argv:
        for arg, func in stat_args:
            if program_arg == arg:
                valid_args_count += 1
                func()

# If no valid arguments were passed prints message about possible argument options
    if valid_args_count == 0:
        for index in range(1, len(sys.argv)):
            args = args + sys.argv[index] + ' '
        print ("Wrong arguments: ", args)
        print('''Argument usage: 
                 Valid arguments are: cpu, mem, disk, ps, self.
                 Use can use multiple arguments separated by space char.
                 Example: metrics.py cpu mem''')


if __name__ == '__main__':
    application()
